import assert from 'node:assert/strict';
import { activateProgram, readPendingProgram, retryPendingProgram, refreshProgram, publishProgram, withExistingRunSchedule } from '../src/utils/trainingProgram.js';
import { programReviewRows, recordProgramReview } from '../src/utils/trainingProgramReview.js';
const storage = new Map();
globalThis.localStorage = { getItem: k => storage.get(k) ?? null, setItem: (k,v) => storage.set(k,String(v)), removeItem: k => storage.delete(k) };
const nutrition = { planId:'n', goalType:'recomp', adjustedIntake:2100, newProtein:150, newCarbs:240, newFat:60 };
const program = { program_id:'retry-1', nutrition };
await assert.rejects(activateProgram('u', program, { post: async () => { throw Error('lost response'); } }));
assert.deepEqual(readPendingProgram('u'), program);
assert.equal(readPendingProgram('another-user'), null);
assert.equal(localStorage.getItem('drvn_nutrition_plan_u'), null);
let sent;
await retryPendingProgram('u', { post: async (url, body) => { sent = body; return { data:{status:'success', nutrition} }; } });
assert.deepEqual(sent, {...program, user_id:'u'});
assert.equal(readPendingProgram('u'), null);
assert.deepEqual(JSON.parse(localStorage.getItem('drvn_nutrition_plan_u')), nutrition);
await assert.rejects(activateProgram('u', program, { post: async () => { throw { response:{status:422} }; } }));
assert.equal(readPendingProgram('u'), null, 'definitive validation rejection must not block a corrected draft');
let resolveRead;
const pendingRead = refreshProgram('u', {get: () => new Promise(resolve => { resolveRead = resolve; })});
publishProgram('u', {nutrition:{...nutrition, planId:'newer'}});
resolveRead({data:{nutrition}});
assert.equal(await pendingRead, false);
assert.equal(JSON.parse(localStorage.getItem('drvn_nutrition_plan_u')).planId,'newer', 'late reads must not replace a newer commit');
localStorage.setItem('u_r_onboarding_cardio_plan', JSON.stringify({plan_id:'r1', start_date:'2026-08-01', total_weeks:1, weeks:[{bricks:[{type:'recovery',status:'pending'}]}]}));
let row = programReviewRows('r', new Date('2026-09-08T12:00:00'))[0];
assert.equal(row.state,'cycle_ended');
assert.match(row.nextAction,/漏記或缺課/);
recordProgramReview(row,'tired',new Date('2026-09-08T12:00:00'));
row = programReviewRows('r',new Date('2026-09-08T12:00:00'))[0];
assert.match(row.nextAction,/恢復偏累/);
assert.equal(row.due,false);
const run = {plan_id:'preserve-run',start_date:'2026-09-01',weeks:[]};
localStorage.setItem('u_u_onboarding_cardio_plan',JSON.stringify(run));
localStorage.setItem('u_u_run_tweaks',JSON.stringify({a:{reduce:true}}));
publishProgram('u',{running:run});
assert.ok(localStorage.getItem('u_u_run_tweaks'),'same-cycle refresh preserves daily adjustments');
assert.deepEqual(withExistingRunSchedule('u',{program_id:'next'},{a:3}).running_schedule,{plan_id:'preserve-run',day_overrides:{a:3}});
console.log('PASS: uncertain-response retry, account isolation, rejected draft recovery, cycle feedback');
